name: PR Checks

on:
  pull_request:
    branches:
      - master  # Modify this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    inputs:
      model_name:
        description: 'The name of the dynamic model'
        required: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your build and test steps her
      - name: Run DBT Command
        run: |
         echo ${{ inputs.model-name }}
